General info about multiclass classifiers
https://scikit-learn.org/stable/modules/multiclass.html

In [21]:
import pandas as pd
from langdetect import detect 
import numpy as np
#!pip install googletrans
from googletrans import Translator

In [26]:
!pip install py-translate

    100% |████████████████████████████████| 61kB 796kB/s ta 0:00:01
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [5]:
train_df = pd.read_excel('/Users/uxuelazkanodobao/Documents/Postgrau-master/Proyecto/train.xlsx')

In [6]:
test_df = pd.read_excel('/Users/uxuelazkanodobao/Documents/Postgrau-master/Proyecto/test.xlsx') 

In [7]:
test_df.head()

Id                                               text  retweet_count  \
0   0  Avui hem représ la Comissió Mixta amb el @gove...             67   
1   1  Torra anunció un "otoño caliente" para aumenta...            856   
2   2  Demà cal sortir als carrers per dir que #Barce...            144   
3   3  “Cercàvem or i vam baixar a la mina.\nI la fos...            338   
4   4  Molt senzill d'entendre, companya: \n1.- L'ALL...           4932   

   favorite_count  
0             103  
1            1501  
2             174  
3            1560  
4            7253

In [8]:
train_df.groupby(['party','username']).size().reset_index()

party         username    0
0   comuns         adacolau  162
1   comuns  xavierdomenechs  158
2       cs    albert_rivera  168
3       cs    inesarrimadas  151
4      erc        joantarda  165
5      erc      martarovira  156
6    jxcat             krls  157
7    jxcat    quimtorraipla  162
8      ppc        albiol_xg  163
9      ppc   santirodriguez  159
10     psc    jaumecollboni  158
11     psc      miqueliceta  161

In [14]:
train_df['language'] = [detect(row['text']) for index, row in train_df.iterrows()]
train_df.head()


Id         username   party  \
0   0      martarovira     erc   
1   1  xavierdomenechs  comuns   
2   2    albert_rivera      cs   
3   3    jaumecollboni     psc   
4   4        albiol_xg     ppc   

                                                text          created_at  \
0  Últim acte de campanya! Aquí tossudament alçat... 2017-12-19 20:12:01   
1  #Badalona necessita uns pressupostos que posin... 2018-04-27 10:04:19   
2  Encuentro Villacís-Valls para lanzar una estra... 2018-11-17 20:34:58   
3  “La palabra es como una bala, no tiene retorno... 2018-10-22 18:10:01   
4  📻 Esta noche, a partir de las 22:10h, me entre... 2018-08-16 10:30:27   

   retweet_count  favorite_count language  
0            785            2295       ca  
1             55              93       ca  
2            357             622       es  
3              4               6       es  
4             20              47       es

In [15]:
train_df['language'] = np.where(train_df.language == 'ca', 1, 0)


In [16]:
train_df.head(9)

Id         username   party  \
0   0      martarovira     erc   
1   1  xavierdomenechs  comuns   
2   2    albert_rivera      cs   
3   3    jaumecollboni     psc   
4   4        albiol_xg     ppc   
5   5    jaumecollboni     psc   
6   6      miqueliceta     psc   
7   7      martarovira     erc   
8   8      miqueliceta     psc   

                                                text          created_at  \
0  Últim acte de campanya! Aquí tossudament alçat... 2017-12-19 20:12:01   
1  #Badalona necessita uns pressupostos que posin... 2018-04-27 10:04:19   
2  Encuentro Villacís-Valls para lanzar una estra... 2018-11-17 20:34:58   
3  “La palabra es como una bala, no tiene retorno... 2018-10-22 18:10:01   
4  📻 Esta noche, a partir de las 22:10h, me entre... 2018-08-16 10:30:27   
5  Escapada de @FeriaLiber per arribar a la prese... 2018-10-02 19:22:47   
6  Brasil se entrega a la extrema derecha, editor... 2018-10-29 08:50:22   
7  "Presunta legitimidad" diu Dastis a @ONU_es\nV... 2017-09-22 05:18:36   
8  Sobre Carmen Alborch: "En la Universitat abrió... 2018-10-25 08:24:51   

   retweet_count  favorite_count  language  
0            785            2295         1  
1             55              93         1  
2            357             622         0  
3              4               6         0  
4             20              47         0  
5              2              17         1  
6             13              29         0  
7           1313            2015         1  
8             15              38         0

In [17]:
print(list(train_df.text))

["Últim acte de campanya! Aquí tossudament alçats i amb un somriure per fer camí cap a la #República. Ho hem dit tan alt que l'Oriol @junqueras, avui, ens ha sentit des d'Estremera! ", '#Badalona necessita uns pressupostos que posin la ciutadania al capdavant i que segueixin recuperant els drets socials que les retallades del PP van eliminar. La transformació a Badalona no es pot aturar. Per això, tot el suport a @mariadolorsa.  \n\n#DolorsAlcaldessa', 'Encuentro Villacís-Valls para lanzar una estrategia electoral común en Madrid y Barcelona ', '“La palabra es como una bala, no tiene retorno” interesante entrevista a \u2066@mcampovidal\u2069  ', '📻 Esta noche, a partir de las 22:10h, me entrevistan en @linternacope. ¡Os espero! ', 'Escapada de @FeriaLiber per arribar a la presentació de “La Otra Cataluña” de @svilasanjuan @EdDestino a la @libreriabernat. Dies com avui ens reafirmen en la millor capitalitat de Barcelona: El llibre! ', 'Brasil se entrega a la extrema derecha, editorial d

In [18]:
import re
from stop_words import get_stop_words

def stop_words():
    """Retrieve the stop words for vectorization -Feel free to modify this function
    """
    return get_stop_words('es') + get_stop_words('ca') + get_stop_words('en')

In [19]:
# Emojis pattern quita todos
emoji_pattern = re.compile("["
                u"\U0001F600-\U0001F64F"  # emoticons
                u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                u"\U0001F680-\U0001F6FF"  # transport & map symbols
                u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                u"\U00002702-\U000027B0"
                u"\U000024C2-\U0001F251"
                u"\U0001f926-\U0001f937"
                u'\U00010000-\U0010ffff'
                u"\u200d"
                u"\u2640-\u2642"
                u"\u2600-\u2B55"
                u"\u23cf"
                u"\u23e9"
                u"\u231a"
                u"\u3030"
                u"\ufe0f"
    "]+", flags=re.UNICODE)


In [28]:
!pip install translator


You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [25]:
translator = Translator()
print(translator.translate(text="hola", dest='ca').text)


JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [15]:
print(translator.translate('Últim acte de campanya! Aquí tossudament alçats i amb un somriure per fer camí cap a la #República. Ho hem dit tan alt que l'),dest='es')#Oriol @junqueras, avui, ens ha sentit des d'Estremera!', dest='es')

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [55]:
from googletrans import Translator 
translator = Translator()
texto = 'Hola buenos dias'
#print(translator.translate(text = texto, dest='es'))


a = translator.translate(texto,dest="es")
print(a)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [16]:
import langdetect
for i in range(len(train_df)):
    if langdetect.detect(train_df["text"][i]) == "ca":
        ori = train_df["text"][i]
        print(ori)
        # Emojis pattern
        emoji_pattern = re.compile("["
                u"\U0001F600-\U0001F64F"  # emoticons
                u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                u"\U0001F680-\U0001F6FF"  # transport & map symbols
                u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                u"\U00002702-\U000027B0"
                u"\U000024C2-\U0001F251"
                u"\U0001f926-\U0001f937"
                u'\U00010000-\U0010ffff'
                u"\u200d"
                u"\u2640-\u2642"
                u"\u2600-\u2B55"
                u"\u23cf"
                u"\u23e9"
                u"\u231a"
                u"\u3030"
                u"\ufe0f"
                "]+", flags=re.UNICODE)
        #emoji_pattern = re.compile("["
        #u"\U0001F600-\U0001F64F"  # emoticons
        #u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        #u"\U0001F680-\U0001F6FF"  # transport & map symbols
        #u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        #                   "]+", flags=re.UNICODE)
        train_df["text"][i]=emoji_pattern.sub(r'', ori)
        a = translator.translate(text = train_df["text"][i],dest="es").text
        print(a.text)
        train_df["traduct"][i] = a.text


Últim acte de campanya! Aquí tossudament alçats i amb un somriure per fer camí cap a la #República. Ho hem dit tan alt que l'Oriol @junqueras, avui, ens ha sentit des d'Estremera! 


/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:31: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [19]:
for index, row in train_df.iterrows():
    #print(emoji_pattern.sub(r'', row['text']))
    #row['text']=emoji_pattern.sub(r'', row['text'])
    if row['language'] == 1:
        #print(translator.translate(text="Bona tarda", dest='es').text)
        #print(translator.translate(text=(emoji_pattern.sub(r'', row['text'])), dest='es').text)
        print(emoji_pattern.sub(r'', row['text']).strip())
    else: 
        print("Esp")

Últim acte de campanya! Aquí tossudament alçats i amb un somriure per fer camí cap a la #República. Ho hem dit tan alt que l'Oriol @junqueras, avui, ens ha sentit des d'Estremera!
#Badalona necessita uns pressupostos que posin la ciutadania al capdavant i que segueixin recuperant els drets socials que les retallades del PP van eliminar. La transformació a Badalona no es pot aturar. Per això, tot el suport a @mariadolorsa.  

#DolorsAlcaldessa
Esp
Esp
Esp
Escapada de @FeriaLiber per arribar a la presentació de “La Otra Cataluña” de @svilasanjuan @EdDestino a la @libreriabernat. Dies com avui ens reafirmen en la millor capitalitat de Barcelona: El llibre!
Esp
"Presunta legitimidad" diu Dastis a @ONU_es
Vaig ser escollida en unes eleccions legals i legítimes! 
I estic complint un mandat democràtic!
Esp
Esp
Esp
Esp
Esp
Estimat @JMatasD i resta de membres de la Sindicadura. Gràcies per la vostra feina. Amb vosaltres, ens jutgen a tots. Som al vostre costat. No acceptarem cap sentència que n

Els diners del rescat se'ls queden i no els tornen, i les despeses de les hipoteques te les fan pagar. Però la culpa que no hi hagi prou diners per a polítiques socials la tenen els grups independentistes perquè no votaran el pressupost del psoe. És clar.
Esp
Esp
Esp
Esp
Endavant, Conseller @ernestmaragall , ara més que mai és vital l’acció exterior catalana.
Esp
Tenim un mandat molt clar i hi estem absolutament compromesos. Llei de transitorietat aprovada! L'#1O decidirem amb seguretat i garanties!
Fa tres anys va irrompre l'esperança del canvi a la ciutat dels prodigis i només és el principi del principi. 

#Barcelona
El meu sentit condol a la família i amics del motorista mort avui a la nostra ciutat. Necessitem la corresponsabilització de tothom per aconseguir que no hi hagi cap víctima més d'accident de trànsit. No ens resignem, volem #BCNVíctimes0
Sorpresa!
Focs fortuïts als jutjats, sobreseïments forçats... a aquest pas només els quedaran els casos contra la democràcia a Catalun

In [33]:
from googletrans import Translator 
#translator = Translator()

#.translator(src='ca', dest='es') 

train_df['traduc'] = np.nan
for index, row in train_df.iterrows():
    #row['text']=emoji_pattern.sub(r'', row['text'])
    if row['language'] == 1:
        print(row['text'])
        traduct = translator.translate(text=row['text'], dest='es').text
        #traduct = translator.translate(text=row['text']).text
        train_df['traduc'] = traduct
        #print(traduct.text)
        
        #print(row['traduccio'])
    else:
        train_df['traduc'] = row['text']

Últim acte de campanya! Aquí tossudament alçats i amb un somriure per fer camí cap a la #República. Ho hem dit tan alt que l'Oriol @junqueras, avui, ens ha sentit des d'Estremera! 
#Badalona necessita uns pressupostos que posin la ciutadania al capdavant i que segueixin recuperant els drets socials que les retallades del PP van eliminar. La transformació a Badalona no es pot aturar. Per això, tot el suport a @mariadolorsa.  

#DolorsAlcaldessa
Escapada de @FeriaLiber per arribar a la presentació de “La Otra Cataluña” de @svilasanjuan @EdDestino a la @libreriabernat. Dies com avui ens reafirmen en la millor capitalitat de Barcelona: El llibre! 
"Presunta legitimidad" diu Dastis a @ONU_es
Vaig ser escollida en unes eleccions legals i legítimes! 
I estic complint un mandat democràtic!
Estimat @JMatasD i resta de membres de la Sindicadura. Gràcies per la vostra feina. Amb vosaltres, ens jutgen a tots. Som al vostre costat. No acceptarem cap sentència que no sigui l’absolució. Abraçades  #P

Quan ens ataquen així, ens reafirmen en la necessitat de que gent comuna com nosaltres estiguem a les institucions per acabar amb el seu classisme, racisme i masclisme: no oblidem mai qui som, d’on venim ni pq estem aquí  
El compromís amb les persones amb discapacitat és absolut i vull desplegar un Pacte Nacional per a les Persones amb Discapacitat amb un impacte directe i real en els seus drets i benestar. Demostrem que som un país capdavanter en integració. 
L’educació és un pilar del nostre país i el Govern tenim clar que només hi ha una cosa més important que les nostres escoles, que sou els mestres i alumnes de les nostres escoles. Bon començament del curs escolar a tot la comunitat educativa!
A la presentación de la campaña #laCatalunyaValiente del @PPCatalunya  amb @Albiol_XG 
La MINORIA política a Catalunya ha pactat unes eleccions AMB LES GARANTIES PER GUANYAR-LES: empresonaments, persecució de l'independentisme, intervencions administratives, quotes de pantalla garantides...

La marxa pels drets civils, socials i nacionals ens ha portat aquest vespre a la Plaça del primer d’octubre. L’hem inaugurada amb l’alcaldessa @karmelafortuny i les entitats. I davant les provocacions, hem fet “un Sant Cugat”: paraula, cançons, alegria i fer la República. 
Esther Niubó reclama un increment de recursos per a la formació permanent del professorat
@eniubo 
Potser la denunciaràs tu, al Congrés no es paguen lloguers! Què us hi apunteu? És democràcia! 
Sobre el Reial Decret aprovat avui i del compromís d’anul.lar les sentències els tribunals franquistes ja!

Cal afrontar la necessitat d’una nova etapa, concentrar totes les nostres forces en la recuperació de l’autogovern, en construir un futur de respecte a la sobirania i al conjunt del poble de Catalunya.

#Investidura 
Avui ens hem posicionat, una vegada més, en favor de la llibertat d’expressió i contra la voluntat del @PPopular de criminalitzar llaços grocs i la solidaritat. 
Gràcies @Jaumeasens per moltes coses, però so

Aquesta tarda ens veiem al tancament de campanya de @ambtumespodem.

Un @podem_cat en moviment per canviar Catalunya i impulsar el canvi a Espanya.

Us hi espero. 
O resistim i avancem o ens conformem amb les injustícies, la por i la violència. Com fa 300 anys, ens trobem en una nova cruïlla històrica pel nostre país. Aquest és el meu missatge amb motiu de la Diada Nacional. 
Hem rebut l’Associació d’Arxivers de Catalunya (@AAC_GD) amb la consellera @LauraBorras. Cal donar un impuls transversal de país en matèria d’arxius i accés a la informació. Tenim un patrimoni documental incalculable. Compten amb el meu suport absolut per una feina decisiva. 
El 21 de desembre tenim una cita ineludible amb les urnes, una cita que entre tots i totes la garantirem #Apoderat21D 
Fent costat @CarlosRemacha @ppvng al #plevng. Es curiós con aquells que reivindiquen democràcia, no deixen parlar. @PPCatalunya 
Avui aprovem un dret subjectiu amb la renda garantida que garanteix la igualtat d'oportunitats i

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [19]:
train_df['text']= [emoji_pattern.sub(r'', row['text']) for index, row in train_df.iterrows()]
train_df['traduc'] = [translator.translate(row['text'], dest='es') for index, row in train_df.iterrows()]
#train_df['traduc'] = [translator.translate(row['text'], dest='es') if row['language']==1 else row['text'] for index, row in train_df.iterrows()]
train_df.head()

KeyboardInterrupt: 

In [52]:
train_df.head()

Id         username   party  \
0   0      martarovira     erc   
1   1  xavierdomenechs  comuns   
2   2    albert_rivera      cs   
3   3    jaumecollboni     psc   
4   4        albiol_xg     ppc   

                                                text          created_at  \
0  Últim acte de campanya! Aquí tossudament alçat... 2017-12-19 20:12:01   
1  #Badalona necessita uns pressupostos que posin... 2018-04-27 10:04:19   
2  Encuentro Villacís-Valls para lanzar una estra... 2018-11-17 20:34:58   
3  “La palabra es como una bala, no tiene retorno... 2018-10-22 18:10:01   
4  📻 Esta noche, a partir de las 22:10h, me entre... 2018-08-16 10:30:27   

   retweet_count  favorite_count  language  \
0            785            2295         1   
1             55              93         1   
2            357             622         0   
3              4               6         0   
4             20              47         0   

                                              traduc  
0  mirad ⬇️⬇️\n\nel # 21D va exactamente de eso:\...  
1  mirad ⬇️⬇️\n\nel # 21D va exactamente de eso:\...  
2  mirad ⬇️⬇️\n\nel # 21D va exactamente de eso:\...  
3  mirad ⬇️⬇️\n\nel # 21D va exactamente de eso:\...  
4  mirad ⬇️⬇️\n\nel # 21D va exactamente de eso:\...

In [22]:
# Preprocess data
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(stop_words=stop_words())
X = vectorizer.fit_transform(train_df['text']).toarray()
y = train_df['party'].values

In [23]:
# pass in array and columns
X = pd.DataFrame(X)

De esta manera le estamos dando el mismo peso a el lengiaje que a todo lo demas, deberíamos de probar a darle mas peso a esta columna


In [24]:
X['language']= train_df['language']
X.head()


0  1  2  3  4  5  6  7  8  9    ...     10882  10883  10884  10885  10886  \
0  0  0  0  0  0  0  0  0  0  0    ...         0      0      0      0      0   
1  0  0  0  0  0  0  0  0  0  0    ...         0      0      0      0      0   
2  0  0  0  0  0  0  0  0  0  0    ...         0      0      0      0      0   
3  0  0  0  0  0  0  0  0  0  0    ...         0      0      0      0      0   
4  0  0  0  0  0  0  0  0  0  1    ...         0      0      0      0      0   

   10887  10888  10889  10890  language  
0      0      0      0      0         1  
1      0      0      0      0         1  
2      0      0      0      0         0  
3      0      0      0      0         0  
4      0      0      0      0         0  

[5 rows x 10892 columns]

In [25]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split

# Split train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

# Naive Bayes classifier
clf = BernoulliNB()
clf.fit(X_train, y_train)
prediction = clf.predict(X_test)
print(np.mean([prediction == y_test]))



0.6208333333333333


In [17]:
# Support Vector Machine Classifier
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
acc_svc = round(svc.score(X_test, y_test) * 100, 2)
acc_svc
scores = cross_val_score(svc, X_train, y_train, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

KeyboardInterrupt: 

In [21]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, y_train)
y_pred = random_forest.predict(X_test)
random_forest.score(X_train, y_train)
acc_random_forest = round(random_forest.score(X_test, y_test) * 100, 2)
acc_random_forest
scores = cross_val_score(random_forest, X_train, y_train, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.64 (+/- 0.06)


In [46]:
#Random Forest Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[33  9 13  5 11  4]
 [ 1 68  0  0  4  2]
 [ 1  2 69 15  2  0]
 [ 0  0 38 42  4  2]
 [ 0  7 10  0 55  5]
 [ 3  9 13  2  7 44]]


In [51]:
#Random Forest Feature importances
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

importances = random_forest.feature_importances_
std = np.std([importances for tree in random_forest.estimators_],
             axis=0)
indices = np.argsort(importances)[::-1]

# Print the feature ranking
print("Feature ranking:")

for f in range(X_train.shape[1]):
    print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))

# Plot the feature importances of the forest
plt.figure()
plt.title("Feature importances")
plt.bar(range(X_train.shape[1]), importances[indices],
       color="r", yerr=std[indices], align="center")
plt.xticks(range(X_train.shape[1]), indices)
plt.xlim([-1, X_train.shape[1]])
plt.show()

Feature ranking:
1. feature 8057 (0.037680)
2. feature 10891 (0.028154)
3. feature 4056 (0.009338)
4. feature 10546 (0.009298)
5. feature 9867 (0.009280)
6. feature 1294 (0.006862)
7. feature 1347 (0.006761)
8. feature 1249 (0.006492)
9. feature 9644 (0.005914)
10. feature 8060 (0.005548)
11. feature 4004 (0.005040)
12. feature 1925 (0.004395)
13. feature 2622 (0.004301)
14. feature 1935 (0.004255)
15. feature 600 (0.004168)
16. feature 4008 (0.003919)
17. feature 6161 (0.003755)
18. feature 1769 (0.003587)
19. feature 4973 (0.003570)
20. feature 1232 (0.003487)
21. feature 3579 (0.003304)
22. feature 5094 (0.003280)
23. feature 5980 (0.003250)
24. feature 9481 (0.003134)
25. feature 1773 (0.003007)
26. feature 4686 (0.002961)
27. feature 8985 (0.002951)
28. feature 3641 (0.002873)
29. feature 9310 (0.002708)
30. feature 10757 (0.002608)
31. feature 10123 (0.002579)
32. feature 2935 (0.002549)
33. feature 8450 (0.002497)
34. feature 10106 (0.002472)
35. feature 5249 (0.002469)
36. feat

KeyboardInterrupt: 

In [22]:
#KNN - K-Nearest Neighbour
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
acc_knn = round(knn.score(X_test, y_test) * 100, 2)
acc_knn
scores = cross_val_score(knn, X_train, y_train, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.30 (+/- 0.04)


In [23]:
#Extra Tree Classifier
from sklearn.ensemble import ExtraTreesClassifier
extra = ExtraTreesClassifier(n_estimators=2000)
extra.fit(X_train, y_train)
y_pred = knn.predict(X_test)
acc_extra = round(knn.score(X_test, y_test) * 100, 2)
acc_extra
scores = cross_val_score(extra, X_train, y_train, cv=5)
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

KeyboardInterrupt: 